---


name: "Shopping Application Image Build & Deployment"


on:

  push:
    branches:
      - production
      
jobs:

  build:

    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      packer_version: "1.9.4"

    
    steps:

      - name: "Repository Checkout"
        uses: actions/checkout@v3
        

      - name: "Packer installation"
        uses: hashicorp/setup-packer@main
        with: 
          version: ${{env.packer_version }}

      - name: "packer init"
        run: packer init .
        working-directory: ./packer/

      - name: "packer validate"
        run: packer validate .
        working-directory: ./packer/
        
      - name: "packer build image"
        run: packer build .
        working-directory: ./packer/
